name: downscaling-notebooks
channels:
  - fastai
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - cdo
  - dask
  - iris
  - jupyterlab
  - metpy
  - nbdev
  - nc-time-axis
  - netcdf4
  - papermill=2
  - pint
  - pip
  - pre-commit
  - pysteps
  - pytest
  - python=3.9.15
  - python-cdo
  - typer
  - xarray
